### ISSUE TITLE
I run classmeet_v02.py

### ISSUE THREAD

**Issue by MX-05** [shubhadeepmandal394/google-meet-automation#1]
this is the error

`Traceback (most recent call last):
  File "c:\Users\mazze\OneDrive\Documenti\GitHub\google-meet-automation\classautomeet_v02.py", line 15, in <module>
    workbook = xlrd.open_workbook('schedule.xls')
  File "C:\Programs\Python\Python39\lib\site-packages\xlrd\__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not `

**Comment by shubhadeepmandal394** [comment]
Hi @MX-05,

It seems that the content in schedule.xls file doesn't go hand in hand with the code. Recheck your code and try again. If the problem still persists then, delete "schedule.xls"  make a new excel sheet add your date, code accordingly and then run the code.

Hope it helped.
